apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kind
spec:
  provider:
    vault:
      server: http://vault.vault-system.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-eso-token
          namespace: vault-system
          key: token
